apiVersion: v1
kind: ConfigMap
metadata:
  name: tamv-identity-config
  namespace: tamv-prod
data:
  NODE_ENV: production
  HOST: 0.0.0.0
  PORT: "8080"
  TAMV_ORCID: "0009-0008-5050-1539"
  TAMV_ZENODO_RECORD: "19436662"
  TAMV_ISNI: "TAMV-ONLINE-0001"
  TAMV_ORG_NAME: "TAMV Online - Infraestructura Soberana"
  TAMV_FOUNDER_NAME: "Edwin Oswaldo Castillo Trejo"
  TAMV_FOUNDER_ALIAS: "Anubis Villaseñor"
  TAMV_DOI_PREFIX: "10.5281"
  TAMV_DID_METHOD: "tamv"
  TAMV_DID_REGION: "rdm"
  TAMV_DID_SERVICE_ENDPOINT: "https://isni.tamv.online/resolve"
