/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WikisRouteImport } from './routes/wikis'
import { Route as NexusRouteImport } from './routes/nexus'
import { Route as Mdx5RouteImport } from './routes/mdx5'
import { Route as KorimaRouteImport } from './routes/korima'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EoctRouteImport } from './routes/eoct'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CspIndexRouteImport } from './routes/csp.index'
import { Route as WikisSlugRouteImport } from './routes/wikis.$slug'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as CspOntologyRouteImport } from './routes/csp.ontology'
import { Route as CspIngestionRouteImport } from './routes/csp.ingestion'
import { Route as CspCanonRouteImport } from './routes/csp.canon'
import { Route as CspAssemblyRouteImport } from './routes/csp.assembly'

const WikisRoute = WikisRouteImport.update({
  id: '/wikis',
  path: '/wikis',
  getParentRoute: () => rootRouteImport,
} as any)
const NexusRoute = NexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => rootRouteImport,
} as any)
const Mdx5Route = Mdx5RouteImport.update({
  id: '/mdx5',
  path: '/mdx5',
  getParentRoute: () => rootRouteImport,
} as any)
const KorimaRoute = KorimaRouteImport.update({
  id: '/korima',
  path: '/korima',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EoctRoute = EoctRouteImport.update({
  id: '/eoct',
  path: '/eoct',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CspIndexRoute = CspIndexRouteImport.update({
  id: '/csp/',
  path: '/csp/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikisSlugRoute = WikisSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WikisRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const CspOntologyRoute = CspOntologyRouteImport.update({
  id: '/csp/ontology',
  path: '/csp/ontology',
  getParentRoute: () => rootRouteImport,
} as any)
const CspIngestionRoute = CspIngestionRouteImport.update({
  id: '/csp/ingestion',
  path: '/csp/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const CspCanonRoute = CspCanonRouteImport.update({
  id: '/csp/canon',
  path: '/csp/canon',
  getParentRoute: () => rootRouteImport,
} as any)
const CspAssemblyRoute = CspAssemblyRouteImport.update({
  id: '/csp/assembly',
  path: '/csp/assembly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRouteWithChildren
  '/eoct': typeof EoctRoute
  '/events': typeof EventsRoute
  '/korima': typeof KorimaRoute
  '/mdx5': typeof Mdx5Route
  '/nexus': typeof NexusRoute
  '/wikis': typeof WikisRouteWithChildren
  '/csp/assembly': typeof CspAssemblyRoute
  '/csp/canon': typeof CspCanonRoute
  '/csp/ingestion': typeof CspIngestionRoute
  '/csp/ontology': typeof CspOntologyRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/wikis/$slug': typeof WikisSlugRoute
  '/csp/': typeof CspIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRouteWithChildren
  '/eoct': typeof EoctRoute
  '/events': typeof EventsRoute
  '/korima': typeof KorimaRoute
  '/mdx5': typeof Mdx5Route
  '/nexus': typeof NexusRoute
  '/wikis': typeof WikisRouteWithChildren
  '/csp/assembly': typeof CspAssemblyRoute
  '/csp/canon': typeof CspCanonRoute
  '/csp/ingestion': typeof CspIngestionRoute
  '/csp/ontology': typeof CspOntologyRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/wikis/$slug': typeof WikisSlugRoute
  '/csp': typeof CspIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/auth': typeof AuthRoute
  '/console': typeof ConsoleRoute
  '/docs': typeof DocsRouteWithChildren
  '/eoct': typeof EoctRoute
  '/events': typeof EventsRoute
  '/korima': typeof KorimaRoute
  '/mdx5': typeof Mdx5Route
  '/nexus': typeof NexusRoute
  '/wikis': typeof WikisRouteWithChildren
  '/csp/assembly': typeof CspAssemblyRoute
  '/csp/canon': typeof CspCanonRoute
  '/csp/ingestion': typeof CspIngestionRoute
  '/csp/ontology': typeof CspOntologyRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/wikis/$slug': typeof WikisSlugRoute
  '/csp/': typeof CspIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/auth'
    | '/console'
    | '/docs'
    | '/eoct'
    | '/events'
    | '/korima'
    | '/mdx5'
    | '/nexus'
    | '/wikis'
    | '/csp/assembly'
    | '/csp/canon'
    | '/csp/ingestion'
    | '/csp/ontology'
    | '/docs/$slug'
    | '/wikis/$slug'
    | '/csp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/auth'
    | '/console'
    | '/docs'
    | '/eoct'
    | '/events'
    | '/korima'
    | '/mdx5'
    | '/nexus'
    | '/wikis'
    | '/csp/assembly'
    | '/csp/canon'
    | '/csp/ingestion'
    | '/csp/ontology'
    | '/docs/$slug'
    | '/wikis/$slug'
    | '/csp'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/auth'
    | '/console'
    | '/docs'
    | '/eoct'
    | '/events'
    | '/korima'
    | '/mdx5'
    | '/nexus'
    | '/wikis'
    | '/csp/assembly'
    | '/csp/canon'
    | '/csp/ingestion'
    | '/csp/ontology'
    | '/docs/$slug'
    | '/wikis/$slug'
    | '/csp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  AuthRoute: typeof AuthRoute
  ConsoleRoute: typeof ConsoleRoute
  DocsRoute: typeof DocsRouteWithChildren
  EoctRoute: typeof EoctRoute
  EventsRoute: typeof EventsRoute
  KorimaRoute: typeof KorimaRoute
  Mdx5Route: typeof Mdx5Route
  NexusRoute: typeof NexusRoute
  WikisRoute: typeof WikisRouteWithChildren
  CspAssemblyRoute: typeof CspAssemblyRoute
  CspCanonRoute: typeof CspCanonRoute
  CspIngestionRoute: typeof CspIngestionRoute
  CspOntologyRoute: typeof CspOntologyRoute
  CspIndexRoute: typeof CspIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wikis': {
      id: '/wikis'
      path: '/wikis'
      fullPath: '/wikis'
      preLoaderRoute: typeof WikisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexus': {
      id: '/nexus'
      path: '/nexus'
      fullPath: '/nexus'
      preLoaderRoute: typeof NexusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mdx5': {
      id: '/mdx5'
      path: '/mdx5'
      fullPath: '/mdx5'
      preLoaderRoute: typeof Mdx5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/korima': {
      id: '/korima'
      path: '/korima'
      fullPath: '/korima'
      preLoaderRoute: typeof KorimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eoct': {
      id: '/eoct'
      path: '/eoct'
      fullPath: '/eoct'
      preLoaderRoute: typeof EoctRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp/': {
      id: '/csp/'
      path: '/csp'
      fullPath: '/csp/'
      preLoaderRoute: typeof CspIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wikis/$slug': {
      id: '/wikis/$slug'
      path: '/$slug'
      fullPath: '/wikis/$slug'
      preLoaderRoute: typeof WikisSlugRouteImport
      parentRoute: typeof WikisRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/csp/ontology': {
      id: '/csp/ontology'
      path: '/csp/ontology'
      fullPath: '/csp/ontology'
      preLoaderRoute: typeof CspOntologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp/ingestion': {
      id: '/csp/ingestion'
      path: '/csp/ingestion'
      fullPath: '/csp/ingestion'
      preLoaderRoute: typeof CspIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp/canon': {
      id: '/csp/canon'
      path: '/csp/canon'
      fullPath: '/csp/canon'
      preLoaderRoute: typeof CspCanonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csp/assembly': {
      id: '/csp/assembly'
      path: '/csp/assembly'
      fullPath: '/csp/assembly'
      preLoaderRoute: typeof CspAssemblyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface WikisRouteChildren {
  WikisSlugRoute: typeof WikisSlugRoute
}

const WikisRouteChildren: WikisRouteChildren = {
  WikisSlugRoute: WikisSlugRoute,
}

const WikisRouteWithChildren = WikisRoute._addFileChildren(WikisRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  AuthRoute: AuthRoute,
  ConsoleRoute: ConsoleRoute,
  DocsRoute: DocsRouteWithChildren,
  EoctRoute: EoctRoute,
  EventsRoute: EventsRoute,
  KorimaRoute: KorimaRoute,
  Mdx5Route: Mdx5Route,
  NexusRoute: NexusRoute,
  WikisRoute: WikisRouteWithChildren,
  CspAssemblyRoute: CspAssemblyRoute,
  CspCanonRoute: CspCanonRoute,
  CspIngestionRoute: CspIngestionRoute,
  CspOntologyRoute: CspOntologyRoute,
  CspIndexRoute: CspIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
